version: "2"

volumes:
  loki-data:

networks:
  backplane:
    external: true
    name: backplane

services:
  loki:
    image: grafana/loki:2.0.0
    networks:
      - backplane
    volumes:
      - loki-data:/tmp
    restart: always